### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by iTrooz** [AudDMusic/firefox-extension#10]
Hey, I noticed you don't have a licence, neither here or on the chrome extension

You might want to add one for these reasons: https://choosealicense.com/no-permission/

**Comment by Mihonarium** [comment]
Thanks for raising the issue!

The code is currently proprietary. If people make contributions, we'll ask them to license those under MIT or something. If there's a need for adding an open-source license, we might consider it, but that seems unnecessary at the moment.
