### ISSUE TITLE
If the video is changed, audio doesn't work on the new one

### ISSUE THREAD

**Issue by Mihonarium** [AudDMusic/firefox-extension#4]
E.g., if you open the extension on YouTube and then go to a different YoTube video, you won't have any sound

**Comment by Mihonarium** [comment]
If you see an extension for Firefox that can record the audio and doesn't break it after the recording stops, please let me know.

(The easiest way to test is on YouTube: if you stop the recording, go to a different video, and it's not muted, then please share a link to that extension.)

**Comment by Termplexed** [comment]
How does this work in regards to tries if one want to test the code? It say it stops after 10 tries. Is that per session?

I wrote up a simple sample to test (executed in Developer-tools web-console (using multi-line editor)) but not able to reproduce:

```js
(() => {
	const wait = ms => new Promise((resolve) => setTimeout(resolve, ms));

	const a = Array.from(
		document.querySelectorAll('audio, video')).filter(
			media => !media.paused
		);
	if (!a.length) {
		console.log('No media playing');
		return;
	}
	const m_elm = a[0];
	console.log(m_elm);
	[
		'readyState', 'paused', 'ended', 
		'duration', 'currentTime', 'mozHasAudio',
		'captureStream', 'mozCaptureStream'
	].forEach(p => console.log(p, m_elm[p]));
	Object.keys(m_elm.attributes).forEach(
		k => console.log(m_elm.attributes[k])
	);
	const mime_a = 'audio/webm';
	const m_cap_str = m_elm.mozCaptureStream();
	const m_cap_str_tracks = m_cap_str.getAudioTracks();
	
	const a_ctx = new AudioContext();
	const m_src = a_ctx.createMediaStreamSource(m_cap_str);
	m_src.connect(a_ctx.destination);
	
	const m_str = new MediaStream(m_cap_str_tracks);
	const m_rec = new MediaRecorder(m_str, {
		mimeType: mime_a
	});
	const rec_data = [];
	m_rec.ondataavailable = evt => {
		console.log('rec_data', evt);
		rec_data.push(evt.data);
	};
	console.log('REC-START');
	m_rec.start();
	
	console.log('----------------');
	console.log(m_cap_str);
	console.log(m_cap_str_tracks);
	
	console.log('----------------');
	console.log(a_ctx);
	console.log(m_src);
	
	console.log('----------------');
	console.log(m_str);
	console.log(m_rec);
	
	const rec_stopped = new Promise((resolve, reject) => {
		m_rec.onstop = resolve;
		m_rec.onerror = evt => reject(evt.name);
	});
	const rec_record = wait(5000).then(() => {
		if (m_rec.state === "recording") {
			console.log('REC-STOP');
			m_rec.stop();
		}
	});
	const rec_playback = chunks => {
		m_elm.muted = true;
		const blob = new Blob(chunks, { type: mime_a });
		const el_a = document.createElement('AUDIO');
		document.body.appendChild(el_a);
		el_a.onended = () => {
			console.log('PLAYBACK-ENDED');
			URL.revokeObjectURL(el_a.src);
			m_elm.muted = false;
			el_a.parentElement.removeChild(el_a);
		};
		el_a.src = URL.createObjectURL(blob);
		console.log('PLAYBACK-START', el_a);
		el_a.play();
	};
	Promise.all([rec_record, rec_stopped]).then(() => {
		console.log('REC-DONE');
		console.log(rec_data);
		rec_playback(rec_data);
	});
})();
```

**Comment by Termplexed** [comment]
OK. Not sure why it did not muted at first, but able to reproduce now.

**Comment by Mihonarium** [comment]
At the moment, the add-on doesn’t have the browser auth that the chrome extension has; you need to sign up at [dashboard.audd.io](https://dashboard.audd.io) and add the api_token in the add-on settings. To test for longer than two weeks or have more than 300 tries, send a hi to api@audd.io, and we’ll add lots of additional tries and time. Sorry about that! I’ll also add this to the readme

**Comment by Mihonarium** [comment]
> OK. Not sure why it did not muted at first, but able to reproduce now.

Thanks for the attempt, in any case!

I tried to somewhat mitigate this by calling [this](https://github.com/AudDMusic/firefox-extension/blob/master/src/popup/popup.js#L813-L824) on [a lot of events](https://github.com/AudDMusic/firefox-extension/blob/master/src/popup/popup.js#L882-L908) that might happen when the video is changed, but there's probably a way better solution.

**Comment by Termplexed** [comment]
I notice that if one do `m_src.connect(a_ctx.destination);` after recording (by my example above), one circumvent the issue as well as if one do `a_ctx.active = false;` followed by `a_ctx.active = true;`

In sample code one get a new issue though as one attach anew each time one run the script (on same video), but in your code you are perhaps looking for / only attaching once.

**Comment by Termplexed** [comment]
Just cloned and ran the extension from FF dev 105. Sounds like the extension suffers from the same issue (though I have not tracked it down) that the sink get attached to the media for each run. I.e. one can hear the volume go up + one get distortion (due to multiple streams on same sink) for each time one open the popup.

**Comment by Mihonarium** [comment]
> one can hear the volume go up 

Hmm, I don't have that. FF dev 105, when the extension is first opened, there's a short break of the audio, but then it works, and the volume doesn't change. Do the console logs display an "injected firefox" every time you open the extension?

I just moved everything to `content.js`.

**Comment by Termplexed** [comment]
Volume increase does not happen on latest. One issue down one to go :P

**Comment by Termplexed** [comment]
OK. Believe I have found a way to fix this. I am somewhat busy now, but write a mock-up later (today I hope).

**Comment by Termplexed** [comment]
The issue at hand is that Firefox destroys the audio sink and it's not able to add new tracks. More information in the *"Firefox-specific notes"* section here:
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream#browser_compatibility
* A few bug reports:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1178751
* https://bugzilla.mozilla.org/show_bug.cgi?id=1259788#c160
* https://bugzilla.mozilla.org/show_bug.cgi?id=1544650
* https://bugzilla.mozilla.org/show_bug.cgi?id=1573031#c4

From what I can find, this should work:

1.) Use `createMediaElementSource()` instead of `createMediaStreamSource()`. This prevents the silencing on source change on media element.
2.) Save the MediaRecorder after setup, if called a second time on same element check if recorder stream is active, if not add the new stream from the capture stream.

Sample code:

```js
const REC = (() => {
	"use strict";

	const wait = ms => new Promise((resolve) => setTimeout(resolve, ms));

	const REC = {
		audio_mime: null,
		audio_data: [],
		audio_recorder: null,
		audio_capture_stream: null,
		get_media_element() {
			const media = Array.from(
				document.querySelectorAll('audio, video')
			).filter(media => !media.paused);
			return media.length ? media[0] : null;
		},
		audio_rec_on_data(evt) {
			REC.audio_data.push(evt.data);
		},
		audio_to_blob() {
			return new Blob(
				REC.audio_data, { type: REC.audio_mime }
			);
		},
		async create_audio_context(m_elm) {
			const a_ctx = new AudioContext();
			// Use createMediaElementSource() instead
			// of createMediaStreamSource()
			const m_src = a_ctx.createMediaElementSource(m_elm);
			m_src.connect(a_ctx.destination);
		},
		create_audio_recorder(m_elm) {
			REC.create_audio_context(m_elm);
			const m_cap_str = m_elm.mozCaptureStream();
			const m_cap_tracks = m_cap_str.getAudioTracks();
			const m_str = new MediaStream(m_cap_tracks);
			const m_rec = new MediaRecorder(m_str, {
				mimeType: REC.audio_mime
			});
			m_rec.ondataavailable = REC.audio_rec_on_data;
			REC.audio_recorder = m_rec;
			REC.audio_capture_stream = m_cap_str;
			return m_rec;
		},
		audio_recorder_add_track() {
			const m_cap_tracks = REC.audio_capture_stream.getAudioTracks();
			REC.audio_recorder.stream.addTrack(m_cap_tracks[0]);
		},
		async audio(rec_time_ms = 2000, mime = 'audio/webm') {
			REC.audio_mime = mime;
			REC.audio_data = [];
			const m_elm = REC.get_media_element();
			if (m_elm === null)
				return Promise.reject('No media playing');
			if (m_elm.dataset.rec !== "initiated") {
				REC.create_audio_recorder(m_elm);
				m_elm.dataset.rec = "initiated";
			} else if (REC.audio_recorder.stream.active === false) {
				/* Track has changed and new is not loaded
				 * automatically. Load new track */
				REC.audio_recorder_add_track();
			}
			const m_rec = REC.audio_recorder;
			m_rec.start();

			const rec_stopped = new Promise((resolve, reject) => {
				/* onstop is raised AFTER dataavailable,
				 * hence REC.buf[] is filled including last
				 * fragment. */
				m_rec.onstop = resolve;
				m_rec.onerror = evt => reject(evt.name);
			});
			const rec_record = wait(rec_time_ms).then(() => {
				if (m_rec.state === "recording")
					m_rec.stop();
			});
			await Promise.all([rec_record, rec_stopped]);
			return REC.audio_to_blob();
		}
	};
	return {
		audio: REC.audio
	};
})();
```

Typically used as:

```js
REC.audio().then(blob => {
	const url = URL.createObjectURL(blob);
	document.getElementById('some-audio-element').src = url;
}).catch(console.warn);
```

**Comment by Termplexed** [comment]
One issue of course is that the recorded media has same volume-level as the playback. E.g. if it is low or muted, recording is also low or muted. Not sure, but ideally would be to get the buffered audio and extract a sample from that (I.e. no recording) but not sure how to achieve that. 

Another alternative could perhaps be to use AudioWorklet

https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet

I got a re-write of this partially working, but would need more time on it + I do not know if it solves anything.

**Comment by Mihonarium** [comment]
Thanks! It seems to work! Can we use the sample code (like, as MIT licensed)?

**Comment by Termplexed** [comment]
> Thanks! It seems to work! Can we use the sample code (like, as MIT licensed)?

Sure, but note that it was not meant as production code, only as a starter :).

**Comment by Termplexed** [comment]
Added a few comments on your commit that you might want to look at.

I have also played around a little with getting a 100% volume recording. One way is to add a gain node that one set to volume level, then set volume to 100%, then record, then reset gain and volume. Result is a 100% volume recording but without volume changing for user; which, I assume, would give better results when checked against the database – but there are a few complications in regards to changing input streams etc.

**Comment by Mihonarium** [comment]
Thanks for the comments! I committed [that](https://github.com/AudDMusic/firefox-extension/commit/1495a09505e1662377665327d67caf7a58b2072d). Please feel free to just edit the code and open a pull request.

Getting a 100% volume sounds great! If you could add it, that would be awesome. (It's probably important to make sure the user doesn't accidentally hear the 100% volume at any point.)

**Comment by Mihonarium** [comment]
We've published the extension: https://addons.mozilla.org/addon/audd/
